from pyengine.main_window.components.color_component import ColorComponent
from pyengine.main_window.components.transform_component import TransformComponent
from pyengine.main_window.components.path_component import PathComponent
from pyengine.main_window.components.sprite_component import SpriteComponent
from pyengine.main_window.components.script_component import ScriptComponent
from pyengine.main_window.components.text_compnent import TextComponent
from pyengine.main_window.components.collision_component import CollisionComponent
