from files.components.component import Component
from files.components.component import Component
from files.components.transform_component import TransformComponent
from files.components.sprite_component import SpriteComponent
from files.components.collision_component import CollisionComponent
from files.components.control_component import ControlComponent
from files.components.text_component import TextComponent
from files.components.auto_component import AutoComponent
from files.components.button_component import ButtonComponent
